### ISSUE TITLE
How to convert images in bin format for SD example ?

### ISSUE THREAD

**Issue by Martoni** [linusreM/Longan-RISC-V-examples#1]
Do you have an example commands to convert an image to a bin format image ?

I want to generate my own pictures[ like these](https://github.com/linusreM/Longan-RISC-V-examples/tree/master/08-SD-card/put_in_tf_card) .

**Comment by linusreM** [comment]
Good point! Should have been added to begin with. Put it in the readme. 
Used this site: [https://lvgl.io/tools/imageconverter](https://lvgl.io/tools/imageconverter)
I cant quite remember whether "Binary RGB565" or "Binary RGB565 Swap" was correct for the configuration used in the display used for the longan boards.

**Comment by Martoni** [comment]
Thanks for this so fast response !

Works for me with "Binary RGB565" but with false color. I will find convert config.
